// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:pills_reminder/core/models/custom_hive_adapters.dart';
import 'package:pills_reminder/core/models/medication_frequency.dart';
import 'package:pills_reminder/core/models/notification_model.dart';
import 'package:pills_reminder/core/models/notification_type.dart';
import 'package:pills_reminder/core/models/weekday.dart';
import 'package:pills_reminder/features/medications/data/models/hive/medication_model_adapter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MedicationFrequencyAdapter());
    registerAdapter(MedicationModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(NotificationListAdapter());
    registerAdapter(DateTimeComponentsAdapter());
    registerAdapter(AndroidScheduleModeAdapter());
    registerAdapter(WeekdayAdapter());
    registerAdapter(TZDateTimeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MedicationFrequencyAdapter());
    registerAdapter(MedicationModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(NotificationListAdapter());
    registerAdapter(DateTimeComponentsAdapter());
    registerAdapter(AndroidScheduleModeAdapter());
    registerAdapter(WeekdayAdapter());
    registerAdapter(TZDateTimeAdapter());
  }
}
