import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'appName': 'Pills Reminder',
      'noPills': 'No Pills Scheduled for Reminder',
      'remaining': 'Remaining Pills:',
      'settings': 'Settings',
      'daily': 'Daily',
      'specificDays': 'Specific Days',
      'once': 'Once',
      'onDay': 'On Day',
      'taken': 'Taken',
      'notTaken': 'Not Taken',
      'medicationName': 'Medication Name',
      'medicationNameHint': 'Please Enter a Name',
      'pAmount': 'Pills Amount (Optional)',
      'pAmountHint': 'Please enter a valid number',
      'frequency': 'Frequency',
      'date': 'Date',
      'selectDate': 'Select Date',
      'toPill': 'Time of Pill',
      'notSet': 'Not Set',
      'timesHint': 'Please Select Time',
      'repeat': 'Amount of Pills Per Day',
      'notificationType': 'Notification Type',
      'inexact': 'Inexact',
      'inexactDescription':
          'Shows notification at roughly specified time, might not work on devices with heavy battery optimizations',
      'exact': 'Exact',
      'exactDescription':
          'Shows notification at exact time, might not work on devices with heavy battery optimizations',
      'alarmClock': 'Alarm Clock',
      'alarmClockDescription':
          'The best option. Shows notification at exact time, Use on devices with heavy battery optimizations like Samsung',
      'sat': 'Sat',
      'sun': 'Sun',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'themeMode': 'Theme Mode',
      'followSystem': 'Follow System',
      'light': 'Light',
      'dark': 'Dark',
      'appsTheme': 'Apps Theme',
      'permissionDenied': 'Permission Denied',
      'notificationsWillNotWork':
          'Notifications will not work until permission is granted.',
      'openSettings': 'Open Settings',
      'notificationTitle': 'Take Your ',
      'notificationBody': 'Time to take your pill',
      'appLange': 'Apps Language',
      'en': 'English',
      'ar': 'Arabic',
      'resetNotifications': 'Reset Notifications',
      'resetNotificationsDescription':
          'This will reset and reschedule all notifications for this medication. ',
      'resetAllNotificationsDescription':
          'This will reset and reschedule all notifications for all medications. ',
      'resetDone': 'All notifications have been reset and rescheduled.',
      'resetWrong':
          'No notifications to reset. Please add a medication first or edit an existing one to register its notifications.',
      'deleteMedication': 'Delete Medication',
      'deleteMedicationDescription':
          'This will delete the medication and its notifications, this action cannot be undone.',
      'deleteDone': 'The medication has been deleted.',
      'cancel': 'Cancel',
      'delete': 'Delete',
    },
    'ar': {
      'appName': 'منبّه الحبوب',
      'noPills': 'لا توجد حبوب مجدولة للتذكير',
      'remaining': 'الكمية المتبقية:',
      'settings': 'الإعدادات',
      'daily': 'يوميًا',
      'specificDays': 'أيام محددة',
      'once': 'مرة واحدة',
      'onDay': 'في اليوم',
      'taken': 'تم التناول',
      'notTaken': 'لم يتم التناول',
      'medicationName': 'اسم الدواء',
      'medicationNameHint': 'من فضلك أدخل اسمًا',
      'pAmount': 'كمية الحبوب (اختياري)',
      'pAmountHint': 'من فضلك أدخل رقمًا صالحًا',
      'frequency': 'التكرار',
      'date': 'التاريخ',
      'selectDate': 'اختر التاريخ',
      'toPill': 'وقت تناول الحبة',
      'notSet': 'غير محدد',
      'timesHint': 'من فضلك اختر الوقت',
      'repeat': 'عدد الحبوب في اليوم',
      'notificationType': 'نوع الإشعار',
      'inexact': 'تقريبي',
      'inexactDescription':
          'يعرض الإشعار في وقت تقريبي، قد لا يعمل على الأجهزة التي تحتوي على تحسينات قوية للبطارية',
      'exact': 'دقيق',
      'exactDescription':
          'يعرض الإشعار في الوقت المحدد تمامًا، قد لا يعمل على الأجهزة التي تحتوي على تحسينات قوية للبطارية',
      'alarmClock': 'منبّه',
      'alarmClockDescription':
          'أفضل خيار. يعرض الإشعار في الوقت المحدد تمامًا. يُستخدم على الأجهزة ذات تحسينات البطارية القوية مثل سامسونج',
      'sat': 'السبت',
      'sun': 'الأحد',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'themeMode': 'وضع المظهر',
      'followSystem': 'اتّباع النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'appsTheme': 'مظهر التطبيق',
      'permissionDenied': 'تم رفض الإذن',
      'notificationsWillNotWork': 'لن تعمل الإشعارات حتى يتم منح الإذن.',
      'openSettings': 'فتح الإعدادات',
      'notificationTitle': 'تناول ',
      'notificationBody': 'حان وقت تناول الحبة',
      'appLange': 'لغة الاتطبيق',
      'en': 'الإنجليزية',
      'ar': 'العربية',
      'resetNotifications': 'إعادة تعين الإشعارات',
      'resetNotificationsDescription':
          'هذا الخيار سيعيد تعين جميع الإشعارات الخاصة بهذا الدواء.',
      'resetAllNotificationsDescription':
          'هذا الخيار سيعيد تعين جميع الإشعارات لجميع الأدوية.',
      'resetDone': 'جميع الإشعارات قد تم إعادة تعينها.',
      'resetWrong':
          'لا توجد إشعارات لإعادة ضبطها. يُرجى إضافة دواء أولاً أو تعديل دواء موجود لتسجيل إشعاراته.',
      'deleteMedication': 'حذف الدواء',
      'deleteMedicationDescription':
          'هذا الخيار سيحذف الدواء وجميع الإشعارات الخاصة به. لا يمكن اعادة الدواء بعد الغاءة',
      'deleteDone': 'تم حذف الدواء وجميع الإشعارات الخاصة به.',
      'cancel': 'الغاء',
      'delete': 'حذف',
    },
  };
}
